### ISSUE TITLE
Nav Optimization

### ISSUE THREAD

**Issue by DibyashaktiMoharana** [DibyashaktiMoharana/ParallaxWebsite#1]
Style the nav links
add a hover pseudostate and change color to #FF3131 and increase the font weight (if possible).
add a transition of 0.3s

**Comment by joshijoe05** [comment]
Hello, I would like to work on this issue, Can you assign this to me?

**Comment by DibyashaktiMoharana** [comment]
> Hello, I would like to work on this issue, Can you assign this to me?

sorry the issue is resolved now
