### ISSUE TITLE
SignUp page 

### ISSUE THREAD

**Issue by DibyashaktiMoharana** [DibyashaktiMoharana/ParallaxWebsite#3]
create a signup page with 2 input fields and 1 button consistent with the site theme and background
link the page to signuip anchor tag

**Comment by joshijoe05** [comment]
Hello,
Can i work on this issue? Assign me

**Comment by deepak04112002** [comment]
@DibyashaktiMoharana Could you please assign the task of creating a signup page with 2 input fields and 1 button, ensuring it's consistent with our site's theme and background? Additionally, please assign the task of linking this page to a signup anchor tag in the website.
